{
 "title": "Spring Boot – Portfolio (Health & Metrics)",
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(http_server_requests_seconds_count{namespace=\"app\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime (min)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    {
     "expr": "(time() - application_started_time_seconds{namespace=\"app\"}) / 60",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "CPU (process %) ",
   "type": "gauge",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage{namespace=\"app\"} * 100",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "JVM Heap Used (MB)",
   "type": "gauge",
   "gridPos": { "x": 12, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "megabytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"app\",area=\"heap\"}) / 1024 / 1024",
     "legendFormat": "heap"
    }
   ]
  },
  {
   "title": "Requests rate (req/s)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{namespace=\"app\"}[5m]))",
     "legendFormat": "all"
    },
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_count{namespace=\"app\"}[5m]))",
     "legendFormat": "status {{status}}"
    }
   ]
  },
  {
   "title": "Request latency p95 (s)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 4, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{namespace=\"app\"}[5m])) by (le))",
     "legendFormat": "p95"
    }
   ]
  },
  {
   "title": "HTTP by outcome",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum by (outcome) (rate(http_server_requests_seconds_count{namespace=\"app\"}[5m]))",
     "legendFormat": "{{outcome}}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{namespace=\"app\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_threads_daemon_threads{namespace=\"app\"}",
     "legendFormat": "daemon"
    }
   ]
  }
 ]
}