apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: app
  namespaceSelector:
    matchNames:
      - app
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s

